### ISSUE TITLE
Installation in Windows 10 with Linux subsystem

### ISSUE THREAD

**Issue by kba** [OCR-D/docs#1]
## Enable Linux subsystem

* Control Panel -> Features
* Linux subsystem for Linux check
* Reboot
* start `bash`

## virtualenv

```sh
python3 -m virtualenv $HOME/venv3
```

## Setup

```
sudo apt-get install python3-pip python3-virtualenv libxrender-dev libxm-dev
sudo make deps-ubuntu
source $HOME/venv3/bin/activate
make deps-pip
make install
```

## Test

```
make test
```

**Comment by VolkerHartmann** [comment]
I had to install Debian after the reboot.
Otherwise start bash fails with missing OS?

**Comment by kba** [comment]
True, need to install a linux distro from "Windows Store" before starting bash.

**Comment by kba** [comment]
https://github.com/OCR-D/ocrd-website/wiki/OCR-D-on-Windows
