### ISSUE TITLE
Setup guide: Translating native commands to docker calls

### ISSUE THREAD

**Issue by tboenig** [OCR-D/docs#12]
please add an example
1. ocrd --version
2. create worksspace
3. create mets and add
+ link to existing and aviable documentation (or snippets) i.e. http://kba.cloud/2019-03-25-dhd/praxis-existing-mets and http://kba.cloud/2019-03-25-dhd/praxis-existing-mets

**Comment by kba** [comment]
* ocrd --version: `docker run --rm ocrd/all ocrd --version`
* create worksspace: `docker run -u $(id -u) -v "$PWD:/data" -w /data ocrd/all ocrd workspace init`
* create mets and add: "create mets" and "create worksspace" are the same thing. Adding to the mets.xml is equivalent, just prepend the docker boilerplate and make sure that the files to be added are already in the data directory.

**Comment by tboenig** [comment]
Thank very much.
